### ISSUE TITLE
Immunization Recommendation Response Message (Stefan Csomor, Advanced Concepts AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#266] opened 2024-09-27 15:39 UTC
ch.fhir.ig.ch-vacd#5.0.0-ballot /immunization-recommendation-response-message.html

not really relevant regarding the ballot content, just a detail in Examples 10.3:, perhaps I'm just not getting it, is an influenca vaccine really recommended against / for patients having ? cholera

Stefan Csomor, Advanced Concepts AG

**Comment by ralych** [comment] 2024-09-27 15:41
duplicate of #258

**Closed** 2024-10-02 05:37 UTC
Labels: duplicate, v5.0.0 - STU 5
